---
title: "Description of nonparametric Repository Contents"
author: "Cynthia M Kroeger"
date: "6/7/2019"
output: github_document
---

This repository contains supporting materials for the manuscript that describes our work evaluating the misuse of nonparametric tests in the presence of heteroscedasticity within nutrition and obesity research. This work further developed and expanded upon research that was presented at Obesity Week 2018 (DOI: 10.5281/zenodo.14800042). 


## Description of Folders:

* __manuscript_materials_2019__: Supporting materials for submitted manuscript: Kroeger CM, Ejima K, Hannon BA, Halliday TM, McComb B, Teran-Garcia M, Dawson JA, Brown AW, King DB, Allison DB. Persistent confusion in nutrition and obesity research about the validity of classic nonparametric tests in the presence of heteroscedasticity: Evidence of the problem and valid alternatives. 
* __conference_materials_2018__: Supporting materials for published conference abstract: Kroeger CM, Hannon BA, Halliday TM, Teran-Garcia M, Allison DB. Misuse of nonparametric tests with heteroscedasticity: A semi-automated review of obesity research. The Obesity Society (TOS): Annual Scientific Meeting. Nashville, Tennessee, USA, 2018.


## Description of Folder Contents 

The types of supporting materials in each folder include: 

* .md/.Rmd file that includes: description of the project, methodological details, descriptions of data and code variables, tips for replication, author contribution and contact information, funding information, and recommended citation information
* .csv file of the data collected 
* .R file with the search strategy, semi-automated data extraction, simulations, and figure generation code
* .txt file with licensing information


## Recommendations for Citation of Supporting Materials  

* __Recommended citation for manuscript_materials_2019__: Kroeger CM and Ejima K. Data and analysis code for manuscript: Persistent confusion in nutrition and obesity research about the validity of classic nonparametric tests in the presence of heteroscedasticity: Evidence of the problem and valid alternatives.
* __Recommended citation for conference_materials_2018__: Kroeger CM. Data and analysis code for published abstract: Misuse of nonparametric tests with heteroscedasticity: A semi-automated review of obesity research. Zenodo. 2018. DOI: 10.5281/zenodo.1480042

